[uwsgi]
module      = run:app
callable    = app
strict      = true

master          = true
harakiri        = 60
buffer-size     = 65535
vacuum          = true
die-on-term     = true
lazy-apps       = true

# Stream logs to stdout/stderr (Docker captures both).
logto           = /dev/stdout
logto2          = /dev/stderr
log-4xx         = /dev/stdout
log-5xx         = /dev/stderr
