[uwsgi]
module      = run:app
callable    = app
strict      = true

log-master      = true
master          = true
harakiri        = 60
buffer-size     = 65535
vacuum          = true
die-on-term     = true
lazy-apps       = true
